name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'

jobs:
  build_on_windows:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        node: [16]
    steps:
      - name: Command
        run: |
          tree /F "C:\Program Files\LLVM"
