name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '**'

jobs:
  build_on_windows:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        node: [16]
    steps:
      - name: Command
        run: |
          choco install wget
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/llvm-13.0.0.src.tar.xz
          tar -zxvf llvm-13.0.0.src.tar.xz
          Cd llvm-13.0.0.src
          cmake -S .-B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cmake --install build
